# ベースイメージとしてRubyを使用
FROM ruby:3.2.2

# ロケールとタイムゾーンの設定
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

# 必要なパッケージのインストール
RUN apt-get update -qq \
    && apt-get install -y ca-certificates curl gnupg build-essential libssl-dev vim \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && NODE_MAJOR=20 \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -qq && apt-get install -y nodejs yarn \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリを作成
RUN mkdir /myapp

# 作業ディレクトリを設定
WORKDIR /myapp

# Bundlerをインストール
RUN gem install bundler

# アプリケーションのファイルをコピー
COPY . /myapp

# ポートを公開
EXPOSE 3000
